import { Inter } from "next/font/google";
import "./globals.css";
/* Component import */
import Navbar from "./components/Navbar.jsx";
import { Grid } from "@mui/material";
import { TaskProvider } from "@/lib/contextApi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Grid container>
          <Grid item lg={3}>

            <Navbar />
          </Grid>
          <Grid item md={9} lg={9} border={"2px solid red"}>
            <TaskProvider>

              {children}

            </TaskProvider>
          </Grid>

        </Grid>
      </body>
    </html>
  );
}
